# Site wide configuration

title: Direction With Intent
description: Think Through. Execute.
logo: DWI.svg # 120x120 px default image used for Twitter summary card
teaser: DWI.svg # 400x250 px default teaser image used in image archive grid
locale:

paginate: 5
paginate_path: "shares/page:num"

# DEV
#url: http://localhost:4000
#base_url: localhost:4000

# PRD
url: http://directionwithintent.com
base_url: directionwithintent.com

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Nuno Valente
  email: nuno.valente@gmail.com
  twitter: nuvan
  google:
    ad-client: ca-pub-5324161887121686
    ad-slot: 3257173456
  bio: 
  avatar: blog_awatar.jpg
disqus-shortname: directionwithintent

og_image: images/directionwithintent-fb.png
og_image_type: image/png
og_image_width: 300
og_image_height: 300

fb_app_id: 761374523954113
fb_profile_id: directionwithintent.com
fb-admins: 1548238448

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
