# Site wide configuration

title: Direction With Intent
description: 
logo: #MainArrow.svg # 120x120 px default image used for Twitter summary card
teaser: #MainArrow.svg # 400x250 px default teaser image used in image archive grid
locale:
# DEV
#url: http://localhost:4000
#base_url: localhost:4000
# PRD
url: http://directionwithintent.com
base_url: directionwithintent.com
# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: nuvan
  email: nuno.valente@gmail.com
  twitter: nuvan
  google:
    ad-client: 
    ad-slot:
  bio: 
  avatar: blog_awatar.jpg
disqus-shortname: directionwithintent


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
