# Site wide configuration

title: Direction With Intent
description: This is a description
logo: MainArrow.svg # 120x120 px default image used for Twitter summary card
teaser: MainArrow.svg # 400x250 px default teaser image used in image archive grid
locale:
# DEV
url: http://localhost:4000
# PRD
#url: http://nuvan.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: nuvan
  email: nuno.valente@gmail.com
  twitter: nuvan
  google:
    ad-client: 
    ad-slot:
  bio: 
  avatar: MainArrow.svg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
